/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../C/JNI_Learn/JNI_Learn/jni.h"
/* Header for class JNI_a */

#ifndef _Included_JNI_a
#define _Included_JNI_a
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_a
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_1a_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     JNI_a
 * Method:    getStringFromC2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_1a_getStringFromC2
  (JNIEnv *, jobject);

/*
 * Class:     JNI_a
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_1a_getKey
  (JNIEnv *, jobject);

/*
 * Class:     JNI_a
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */


#ifdef __cplusplus
}
#endif
#endif
